PKGDIR	?= ..
L4DIR	?= $(PKGDIR)/../../../l4re-snapshot-21.07.0/src/l4

# All header files found in this directory tree will be automatically
# installed in a way that they can be included with
# #include <l4/pkgname/yourfile.h> later.
# No need to list them in this Makefile.

#CONTRIB_HEADERS = y
#INCSRC_DIR      = $(SRC_DIR)/../server/src/include

include $(L4DIR)/mk/include.mk
