PKGDIR ?= ..
L4DIR  ?= $(PKGDIR)/../../../l4re-snapshot-21.07.0/src/l4

# create examples demonstrating the use of your package in subdirectories
# and list those subdirs in the TARGET variable.
TARGET =

include $(L4DIR)/mk/subdir.mk
